### ISSUE TITLE
New DB structure - TID Question

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/CodenameIndigo#20]
The Problem
-----------
As @jdsaphir stated in #19 and a continuation from #18 

>each time information about the tournament is requested, it is with tournament ID tid=1, it should use the tourney for which the date is compatible [for example : if registrations are currently open for the fourth tourney we organize, it should use tid=4 based on the dates] 

Details
-------
Should we just then always use the highest tid, since it's auto increment? or check for latest date? What do we want to do if there's multiple tourney's still within the time frame?

**Comment by jdsaphir** [comment]
Ideally, only the dates should be taken into account to determine which tourney is open for registration. If more than one are, the user should be able to choose which one to register for (that's why I added a tournament name field, so it is more convivial than "tournament 42", and allows you to actually take something from the DB for your [TOURNEY_NAME] in the registration command).

**Comment by dylanpiera** [comment]
In that case I'll start working on that 🔜
