### ISSUE TITLE
Game Setup + Settings

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/CodenameIndigo#3]
I'm planning on adding a tournament setup for admins, what options should be available?

- Signup End Date
- Min/Max Player Amount?
- ???

**Comment by jdsaphir** [comment]
- Check a user's team
- Remove a user (if the team is not in conformity with the rules or whatever reason)
- Set a user as E4 or Champ for this tournament (unless it's managed automatically)
- ???

**Comment by dylanpiera** [comment]
@DN do we want the E4 to be automated or not?

**Comment by jdsaphir** [comment]
If so, the user should be made able to change their team, unless we don't want the E4/Champ to be able to change their team between tournaments...

**Comment by jdsaphir** [comment]
DN says they should be able to, so either make it manual, or add the option to edit your team for as long as registrations are still open.

**Comment by dragonnataku** [comment]
I dunno about min/max (well min would have to be at least two ww but considering how many staff want to be involved already I think we'd have at least 16 from the get-go).  I think that we should leave max open for the first live tourney since we won't know how many people will sign up and we don't want to leave people out.
